### ISSUE TITLE
Notifications continue to repeat/build up

### ISSUE THREAD

**Issue by jasontwong** [squaresurf/objective-octocat-notifications#39] opened 2015-12-16 20:30 UTC
Leaving my computer on and letting it go into screensaver mode but not sleep constantly requests the GitHub notifications. (e.g. 10 notifications * 5 hours of sleep = 150 notifications in my notification center)

**Comment by squaresurf** [comment] 2015-12-16 22:19
Are they the same notifications? (i.e. duplicates)

**Comment by jasontwong** [comment] 2015-12-16 22:58
Yup. It's as if it downloads the whole array of notifications over and over again. I can record a screen shot of some sort the next time it happens.

**Comment by squaresurf** [comment] 2015-12-17 00:10
I'll try and repro, then let you know how it goes.

**Comment by squaresurf** [comment] 2015-12-17 22:42
@jasontwong I can't seem to repro this issue. It seems as though the app can't ask for the current notifications in the user notification center. Do you have any ideas for why it would be blocked while your screensaver is running?

I would love some screenshots.

**Comment by jasontwong** [comment] 2015-12-18 03:39
Yeah. I'll let you know when it happens. I think I see it mostly when pull requests are being made. It's as if it reloads the entire GitHub notification each time. It happens about once a week so I'll try to show you when I get the chance.

**Comment by squaresurf** [comment] 2015-12-18 13:38
Awesome. Thank you.

**Comment by jasontwong** [comment] 2015-12-22 03:16
Here's how many notifications I came back to today! It's only the total number and I keep getting notified of PR's. But the notification bar stays the same.
![lwscreenshot 2015-12-21 at 10 14 18 pm](https://cloud.githubusercontent.com/assets/1128472/11947110/5c5e5c06-a830-11e5-8d82-f79b583d0049.png)

**Comment by squaresurf** [comment] 2015-12-22 15:16
:disappointed: I'll take a look at the code here soon to see if I can figure this out. The hardest part though is that I can't reproduce it which makes it difficult to know if it's fixed by my changes.

**Comment by jasontwong** [comment] 2015-12-23 01:53
Just got back to my computer without sleeping and not touch any notifications and it built up more. LOL.

Not a biggie. I just have to clear out my GitHub notifications by logging in and going through them.

![lwscreenshot 2015-12-22 at 8 50 26 pm](https://cloud.githubusercontent.com/assets/1128472/11969815/ea1a71b6-a8ed-11e5-92be-1445442e8622.png)

**Comment by squaresurf** [comment] 2015-12-23 13:33
Oh, so you have that many notifications on github?

**Comment by jasontwong** [comment] 2015-12-23 15:59
Nope. It's just that the counter keeps building up. But the notifications in the notification bar stay the same...

**Comment by squaresurf** [comment] 2015-12-23 16:09
Ah, that helps a lot. So there aren't 608 notifications in your mac user notification center? It's just that the count keeps going up for the main notification?

**Comment by jasontwong** [comment] 2015-12-23 20:14
Yup. It just keeps going up. And the notifications keep appearing as if they are new. But they aren't.

**Comment by squaresurf** [comment] 2016-01-13 14:43
I've been able to repro this issue! It appears that the bug occurs when there are more than 20 notifications in github. I will need to re-architect how I'm checking if a notification has been shown or not.

**Comment by squaresurf** [comment] 2016-01-13 20:43
@jasontwong I think my fix for this will be to create a notification with the count of notifications and when clicked will take you to the github notification panel as any more than 20 notifications is not very useful in the mac notification center. It will also clear out the other notifications and only have the one with the total notification count. Do you think that would be useful for you?

**Comment by jasontwong** [comment] 2016-01-13 20:55
Is that functionality on top of the current one? So it's individual but once it builds up past a certain point it will have a number and take me to notifications? I think going to the notifications page works pretty well. Especially once you have a lot (20+).

**Comment by squaresurf** [comment] 2016-01-13 21:24
Yes, it will only switch to a count once you reach > 20 notifications in the mac notification panel.

**Comment by jasontwong** [comment] 2016-01-13 23:05
Yeah. That sounds awesome.

**Closed** 2016-01-14 16:06 UTC
Labels: bug
